version: 2

models:
  - name: dim_customers
    description: >
      Dimension table for customers. Contains surrogate keys and current
      descriptive attributes like name and email.
    columns:
      - name: customer_sk
        description: Surrogate key for the customer (used in fact tables).
        tests:
          - not_null
          - unique
      - name: customer_id
        description: Natural business key of the customer.
        tests:
          - not_null
          - unique
      - name: customer_name
        description: Full name of the customer.
      - name: customer_email
        description: Customer's email address.
      - name: load_timestamp
        description: Timestamp when the dimension record was loaded.

  - name: dim_dates
    description: >
      Date dimension table spanning from 2016-01-01 to 2025-12-31. Provides
      surrogate keys, calendar breakdowns, and formatted fields for analysis.
    columns:
      - name: date_sk
        description: Surrogate key for the date in YYYYMMDD format.
        tests:
          - not_null
          - unique
      - name: date_actual
        description: Actual calendar date.
        tests:
          - not_null
          - unique
      - name: year
        description: Year of the date.
      - name: month
        description: Month number of the date (1–12).
      - name: day
        description: Day of month (1–31).
      - name: month_name
        description: Name of the month (e.g., January).
      - name: day_name
        description: Name of the day of the week (e.g., Mon).
      - name: quarter
        description: Quarter of the year (1–4).
      - name: load_timestamp
        description: Timestamp when the dimension record was loaded.

  - name: dim_products
    description: >
      Dimension table for products. Contains surrogate keys, descriptive
      attributes, and current pricing information.  
    columns:
      - name: product_sk
        description: Surrogate key for the product (used in fact tables).
        tests:
          - not_null
          - unique
      - name: product_id
        description: Natural business key of the product.
        tests:
          - not_null
          - unique
      - name: product_name
        description: Name of the product.
      - name: product_type
        description: Type/category of the product (e.g., Jaffle, Beverage).
      - name: product_price
        description: Price of the product (in euros).
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 4
              max_value: 14
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
      - name: load_timestamp
        description: Timestamp when the dimension record was loaded.

  - name: dim_stores
    description: >
      Dimension table for store locations. Contains surrogate keys, store IDs,
      and location names.
    columns:
      - name: store_sk
        description: Surrogate key for the store (used in fact tables).
        tests:
          - not_null
          - unique
      - name: store_id
        description: Natural business key of the store.
        tests:
          - not_null
          - unique
      - name: location_name
        description: Human-readable location name for the store.
        tests:
          - accepted_values:
              values: ["San Francisco", "Brooklyn", "Chicago", "Los Angeles", "New Orleans", "Philadelphia"]
      - name: load_timestamp
        description: Timestamp when the dimension record was loaded.
