version: 2

sources:
    - name: jaffle
      schema: RAW_SCHEMA
      tables:
        - name: customers
          identifier: RAW_CUSTOMERS

        - name: orders
          identifier: RAW_ORDERS

        - name: order_items
          identifier: RAW_ORDER_ITEMS

        - name: products
          identifier: RAW_PRODUCTS

        - name: supplies
          identifier: RAW_SUPPLIES

        - name: stores
          identifier: RAW_STORES