version: 2

sources:
    - name: jaffle
      schema: RAW_SCHEMA
      description: "Raw source data for the Jaffle Shop project. 
      These tables are ingested as-is from the source system.
      The staging models (stg_*) will transform them into clean, analytics-ready datasets."

      tables:

        - name: customers
          identifier: RAW_CUSTOMERS
          description: Raw customers table containing one row per customer.


        - name: orders
          identifier: RAW_ORDERS
          description: Raw orders table containing one row per order. 


        - name: order_items
          identifier: RAW_ORDER_ITEMS
          description: Line-level details of items within an order.


        - name: products
          identifier: RAW_PRODUCTS
          description: Raw product master data. 


        - name: supplies
          identifier: RAW_SUPPLIES
          description: Supplies data related to product sourcing and vendors.


        - name: stores
          identifier: RAW_STORES
          description: Raw store master data with location details